nodeLinker: node-modules

supportedArchitectures:
  libc:
    - current
    - libc
    - musl
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
