version: '3.7'
services:
  kratos-migrate:
    depends_on:
      - postgres
    image: eu.gcr.io/serlo-shared/kratos:0.11.1-custom
    volumes:
      - ./kratos:/etc/config/kratos:z
    command: -c /etc/config/kratos/config.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: eu.gcr.io/serlo-shared/kratos:0.11.1-custom
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/config.yml --dev --watch-courier
    volumes:
      - ./kratos:/etc/config/kratos:z
    networks:
      - intranet
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:z
    environment:
      - POSTGRES_USER=serlo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet
  mailslurper:
    # TODO: use image: marcopas/docker-mailslurper:latest or another maintained project
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
  nbp:
    image: quay.io/keycloak/keycloak:21.0.0
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - intranet
networks:
  intranet:
