version: '3.9'
services:
  db-layer:
    image: eu.gcr.io/serlo-shared/serlo-org-database-layer:${DB_LAYER_VERSION}
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    command: ./server
    environment:
      - DATABASE_MAX_CONNECTIONS=5
      - DATABASE_URL=mysql://root:secret@mysql:3306/serlo
      - ENV=development
    networks:
      - intranet
