version: '3.9'

services:
  mysql:
    build:
      context: mysql/docker-container
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=serlo
    networks:
      - intranet
