version: '3.9'
services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d:z
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - intranet
