version: '3.7'
services:
  import-users-job:
    depends_on:
      - kratos-migrate
      - kratos
    image: node:16
    volumes:
      - ./kratos/import-users.js:/tmp/import-users.js
      - ./kratos/legacy-password-hash-service.js:/tmp/legacy-password-hash-service.js
    working_dir: /tmp
    # TODO: update to a more up-to-date @ory/client version
    command: "bash -c 'yarn init --yes && yarn add js-sha1 mysql @ory/client@0.2.0-alpha.4 && node import-users.js'"
    restart: on-failure
    networks:
      - intranet
    extra_hosts:
      - 'host.docker.internal:host-gateway'
