version: '3.7'
services:
  hydra:
    image: oryd/hydra:v1.11.8
    ports:
      - '4444:4444'
      - '4445:4445'
    command: serve all --dangerous-force-http
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
    environment:
      - LOG_LEVEL=debug
      - LOG_LEAK_SENSITIVE_VALUES=true
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=1
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_LOGIN=http://localhost:3000/auth/oauth/login
      - URLS_LOGOUT=http://localhost:3000/auth/oauth/logout
      - URLS_CONSENT=http://localhost:3000/auth/oauth/consent
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
    networks:
      - intranet
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    restart: on-failure
    environment:
      MONGO_URL: 'mongodb://mongodb:27017/rocketchat?replicaSet=rs0'
      MONGO_OPLOG_URL: 'mongodb://mongodb:27017/local?replicaSet=rs0'
      ROOT_URL: http://localhost:3030
      PORT: '3030'
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb
    expose:
      - '3030'
    ports:
      - '${BIND_IP:-0.0.0.0}:${HOST_PORT:-3030}:3030'
    networks:
      - intranet
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
      # FIXME: investigate if dump has correct configurations
      - ./dump:/dump
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: '27017'
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: '27017'
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: 'true'
      ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - intranet
networks:
  intranet:
volumes:
  mongodb_data: { driver: local }
  hydra-sqlite:
